ProyectoSIGEM/Areas/Interna/Controllers/IntHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoSIGEM.Areas.Interna.Controllers
{
    //[Authorize(Roles = "Admin,Empleado")]
    public class IntHomeController : Controller
    {
        // GET: Interna/IntHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoSIGEM/Areas/Interna/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Área Interna</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Proyecto SIGEC", "Index", "IntHome", new { area = "Interna" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">s
                    <li>@Html.ActionLink("Alumnos", "Index", "Alumnos", new { area = "Interna" },null)</li>
                    <li>@Html.ActionLink("Escuelas", "Index", "Escuelas", new { area = "Interna" }, null)</li>
                    <li>@Html.ActionLink("Matrículas", "Index", "Matriculas", new { area = "Interna" }, null)</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>