ProyectoSIGEM/Areas/Externa/Controllers/AlumnoPubController.cs
using AutoMapper;
using ProyectoSIGEM.Areas.Interna.Models;
using ProyectoSIGEM.Servicios.Matriculas;
using ProyectoSIGEM.Servicios.Matriculas.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoSIGEM.Areas.Externa.Controllers
{
    [Authorize(Roles = "Empleado, Admin")]
    public class AlumnoPubController : Controller
    {
        private ServicioMatriculas servicioMatriculas;

        public AlumnoPubController()
        {
            servicioMatriculas = new ServicioMatriculas();
        }

        // GET: Externa/Alumno
        public ActionResult Index(string busqueda)
        {
            var model = Mapper.Map<IList<MatriculaDto>, IList<MatriculasListaViewModel>>(servicioMatriculas.Buscar(busqueda));
            return View(new BuscaMatriculasViewModel() { Matriculas = model });
        }

        public PartialViewResult ConsultarMatriculasPub(string busqueda)
        {
            var model = Mapper.Map<IList<MatriculaDto>, IList<MatriculasListaViewModel>>(
                servicioMatriculas.Buscar(busqueda));

            return PartialView("_ListaMatric", model);
        }
    }
}

ProyectoSIGEM/Areas/Externa/Views/AlumnoPub/Index.cshtml
@model ProyectoSIGEM.Areas.Externa.Models.BuscaMatriculasViewModel



@using (Ajax.BeginForm("ConsultarMatriculasPub", "AlumnoPub", new AjaxOptions
{
    HttpMethod = "Get",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "AlumnoPubListContainer"
}, new
{
    id = "ConsultarMatriculasPubForm",
    @class = "form-horizontal"
}))
{
    <div class="form-group col-sm-10">
        <input type="text" placeholder="Ingresar documento de identidad..."
               name="Busqueda" class="form-control" value="@Model.Busqueda" />
    </div>
    <div class="col-sm-2">
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-search"></i></button>
    </div>

}
<div id="AlumnoListContainer">

</div>
<div id="RenuevaModalFormContainer" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="checkInFormLabel" aria-hidden="True"></div>
@section Scripts {
    @Scripts.Render("~/bundles/unobtrusive")
}

ProyectoSIGEM/Areas/Externa/Views/AlumnoPub/_ListaMatric.cshtml
@model IEnumerable<ProyectoSIGEM.Areas.Externa.Models.MatriculasListaViewModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            N° Matrícula
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EscuelaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EscuelaEmisora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Curso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CostoTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FecIngreso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Observacion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MatriculaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EscuelaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EscuelaEmisora)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Curso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CostoTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FecIngreso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Observacion)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>